overrides:
  - files: "*.{ts,js}"
    options:
      semi: true
      singleQuote: true
      bracketSpacing: false
      trailingComma: none
      arrowParens: avoid
  - files: "*.{css,scss}"
    options:
      semi: true
      singleQuote: false
      bracketSpacing: false
