overrides:
  - files: "*.{ts,js,mjs}"
    options:
      semi: true
      singleQuote: true
      bracketSpacing: false
      trailingComma: es5
      arrowParens: avoid
  - files: "*.{css,scss}"
    options:
      semi: true
