extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier-scss
rules:
  # override default values
  color-function-notation: legacy #recommanded "modern" value leads to build errors
  color-hex-length: long
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - transition #too many properties are summarised with this one
  declaration-empty-line-before: never
  no-invalid-position-at-import-rule:
    - true
    - ignoreAtRules:
        - use
        - forward
        - include
  number-max-precision: 6
  property-no-vendor-prefix:
    - true
    - ignoreProperties:
        - appearance # experimental rule, that don't behave the same without prefix
        - text-size-adjust # experimental rule, that don't behave the same without prefix
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
        - ng-deep
  value-keyword-case:
    - lower
    - ignoreKeywords:
        - Arial
        - Roboto
        - BlinkMacSystemFont
  scss/at-mixin-argumentless-call-parentheses: always
  # deactivate unwanted rules
  scss/double-slash-comment-empty-line-before: null
  # rules that need some refactoring to be enabled
  no-descending-specificity: null
  selector-class-pattern: ^([a-z][a-z0-9]*)([-_]{0,2}[a-z0-9]+)*$
