extends: "../../.eslintrc.yml"
ignorePatterns:
  - "!**/*"
overrides:
  - files:
      - "*.ts"
    parserOptions:
      project:
        - projects/stylesBuilder/tsconfig.styles.json
    rules:
      # rules that need some refactoring to be enabled
      "@typescript-eslint/no-unnecessary-condition": off
      "@typescript-eslint/prefer-nullish-coalescing": off
      "@typescript-eslint/strict-boolean-expressions": off
