extends: "../../.stylelintrc.yml"
rules:
  # rules that need some refactoring to be enabled
  no-descending-specificity: null
  selector-id-pattern: null
  selector-class-pattern: ^([a-z][a-z0-9]*)([-_]{0,2}[a-z0-9]+)*$
