extends: "../../.eslintrc.yml"
ignorePatterns:
  - "!**/*"
overrides:
  - files:
      - "*.ts"
    parserOptions:
      project:
        - projects/oblique/tsconfig.lib.json
        - projects/oblique/tsconfig.spec.json
    rules:
      "@angular-eslint/directive-selector":
        - error
        - type: attribute
          prefix: ob
          style: camelCase
      "@angular-eslint/component-selector":
        - error
        - type: element
          prefix: ob
          style: kebab-case

        # rules that needs some refactoring before being activated
      "@angular-eslint/sort-lifecycle-methods": off
