name: Bug Report
description: Report a bug in Oblique

body:
  - type: input
    id: ob-version
    attributes: 
      label: Oblique version
    validations:
      required: true

  - type: input
    id: browser-version
    attributes: 
      label: Browser & version
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node version
    validations:
      required: false

  - type: input
    id: device
    attributes: 
      label: Device and operating system
    validations:
      required: false

  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - "Yes"
        - "No"
        - "I don't know"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes: 
      label: Screenshots
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      render: true
      label: Description
      placeholder: Provide a clear and concise description of the bug you are experiencing
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      render: true
      label: Reproduction
      placeholder: Explain how this bug can be reproduced
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      render: true
      label: Expected behaviour
      placeholder: Explain what you expected to happen instead of the bug
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      render: true
      label: Context
      placeholder: Provide any additional information we might need to resolve this bug
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      render: true
      label: Proposed solution
      placeholder: Share your idea on how this could be implemented
    validations:
      required: false
