#!/usr/bin/env node
/**
 * build-howto.js — Creates the "How to maintain this file" frame on the
 * 🎨 Colors – Contrast Pairings page, cloned from the equivalent frame on
 * the Colors – Maintainer page (node 9544:35564) and updated for contrast pairings.
 *
 * Usage:
 *   node build-howto.js
 *
 * Prerequisites:
 *   - Figma Desktop open with DesignSystem@Tokens V9.6 (51tJjbxBSBmjAmKjQmhsz3)
 *   - Desktop Bridge plugin running (Plugins → Development → Figma Desktop Bridge)
 *   - FIGMA_ACCESS_TOKEN env var set (or hard-coded below for dev)
 */
'use strict';
const { spawn } = require('child_process');

// ─── Config ─────────────────────────────────────────────────────────────────

const FIGMA_ACCESS_TOKEN = process.env.FIGMA_ACCESS_TOKEN;
const TIMEOUT_MS = 30000;
const INIT_TIMEOUT_MS = 15000;

// ─── Stdio MCP Client ────────────────────────────────────────────────────────

class StdioMCPClient {
  constructor() {
    this.process = null;
    this.requestId = 0;
    this.pending = new Map();
    this.buffer = '';
    this.ready = false;
  }

  async start() {
    return new Promise((resolve, reject) => {
      const env = { ...process.env, FIGMA_ACCESS_TOKEN, ENABLE_MCP_APPS: 'true' };

      this.process = spawn('npx', ['-y', 'figma-console-mcp@latest'], {
        env,
        stdio: ['pipe', 'pipe', 'pipe'],
        shell: false,
      });

      let stderrBuf = '';
      this.process.stderr.on('data', (chunk) => {
        stderrBuf += chunk.toString();
        const lines = stderrBuf.split('\n').filter(Boolean);
        const last = lines[lines.length - 1] || '';
        if (last.includes('ERROR') || last.includes('error')) {
          process.stderr.write('  [mcp] ' + last + '\n');
        }
      });

      this.process.stdout.on('data', (chunk) => {
        this.buffer += chunk.toString();
        this._processBuffer();
      });

      this.process.on('error', (err) => reject(new Error('Failed to start: ' + err.message)));
      this.process.on('exit', (code) => {
        if (!this.ready) reject(new Error('Exited prematurely (code ' + code + ')\n' + stderrBuf.slice(-400)));
        for (const [, p] of this.pending) { clearTimeout(p.timer); p.reject(new Error('Process exited')); }
        this.pending.clear();
      });

      setTimeout(async () => {
        try { await this._initialize(); this.ready = true; resolve(); }
        catch (err) { reject(err); }
      }, 2000);
    });
  }

  async _initialize() {
    await this._send('initialize', {
      protocolVersion: '2024-11-05',
      capabilities: {},
      clientInfo: { name: 'build-howto', version: '1.0.0' },
    }, INIT_TIMEOUT_MS);
    this._sendNotification('notifications/initialized');
  }

  async execute(code, timeout = TIMEOUT_MS) {
    const result = await this._send('tools/call', {
      name: 'figma_execute',
      arguments: { code, timeout },
    }, timeout + 5000);

    if (result && result.content) {
      for (const item of result.content) {
        if (item.text) {
          try { return JSON.parse(item.text); } catch { return item.text; }
        }
      }
    }
    return result;
  }

  _send(method, params, timeout = TIMEOUT_MS) {
    return new Promise((resolve, reject) => {
      const id = ++this.requestId;
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`Timeout after ${timeout}ms for ${method}`));
      }, timeout);
      this.pending.set(id, { resolve, reject, timer });
      this.process.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n');
    });
  }

  _sendNotification(method, params) {
    this.process.stdin.write(JSON.stringify({ jsonrpc: '2.0', method, params }) + '\n');
  }

  _processBuffer() {
    const lines = this.buffer.split('\n');
    this.buffer = lines.pop();
    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        const msg = JSON.parse(line);
        if (msg.id && this.pending.has(msg.id)) {
          const { resolve, reject, timer } = this.pending.get(msg.id);
          clearTimeout(timer);
          this.pending.delete(msg.id);
          if (msg.error) reject(new Error(msg.error.message || JSON.stringify(msg.error)));
          else resolve(msg.result);
        }
      } catch { /* non-JSON line, skip */ }
    }
  }

  stop() {
    if (this.process) {
      this.process.stdin.end();
      this.process.kill('SIGTERM');
      this.process = null;
    }
  }
}

// ─── Figma-side code (runs inside Figma Desktop via the plugin bridge) ────────

const FIGMA_CODE = /* js */ `
(async () => {
  const SPEC = {
    targetPage:    '9559:21413',  // 🎨 Colors – Contrast Pairings
    sourceFrame:   '9544:35564',  // "How to maintain this file" on Maintainer page
    buildingBlocks:'9628:44885',  // "Building Blocks" section on Contrast Pairings page
  };

  const INTRO_TEXT = [
    'This page is generated by scripts in scripts-custom/figma-builders/contrast-pairings/.',
    'Run the commands below to rebuild the contrast pairings from the live token values in Figma.',
  ].join('\\n');

  const COMMANDS_TEXT = [
    'scripts-custom/figma-builders/contrast-pairings/',
    '',
    '# Rebuild all 3 categories (neutral + interaction + status)',
    'node mcp-executor.js --all',
    '',
    '# Rebuild a single category',
    'node mcp-executor.js neutral',
    'node mcp-executor.js interaction',
    'node mcp-executor.js status',
    '',
    '# Extract current swatch state from Figma to JSON',
    'node mcp-executor.js --extract',
  ].join('\\n');

  // Load fonts used by the cloned text nodes
  const FONTS = [
    { family: 'Noto Sans', style: 'Bold' },
    { family: 'Noto Sans', style: 'SemiBold' },
    { family: 'Noto Sans', style: 'Regular' },
    { family: 'Inter', style: 'Regular' },
  ];
  await Promise.all(FONTS.map(f => figma.loadFontAsync(f)));

  await figma.loadAllPagesAsync();

  const targetPage = figma.root.children.find(p => p.id === SPEC.targetPage);
  if (!targetPage) return { error: 'Target page not found: ' + SPEC.targetPage };

  // Guard: do not create a duplicate
  const existing = targetPage.findOne(n => n.name === 'How to maintain this file');
  if (existing) {
    return { skipped: true, message: 'Already exists (id: ' + existing.id + '). Delete it first to recreate.' };
  }

  const sourceFrame = await figma.getNodeByIdAsync(SPEC.sourceFrame);
  if (!sourceFrame) return { error: 'Source frame not found: ' + SPEC.sourceFrame };

  // Clone the reference frame onto the target page
  const cloned = sourceFrame.clone();
  targetPage.appendChild(cloned);

  // Position: 64px below the Building Blocks section, left-aligned with it
  const buildingBlocks = await figma.getNodeByIdAsync(SPEC.buildingBlocks);
  if (buildingBlocks) {
    cloned.x = buildingBlocks.x;
    cloned.y = buildingBlocks.y + buildingBlocks.height + 64;
  } else {
    cloned.x = -2998;
    cloned.y = 2500;
  }

  // Update text content for the Contrast Pairings-specific copy
  function findChild(node, name) {
    return (node.children || []).find(c => c.name === name) || null;
  }

  const introNode    = findChild(cloned, 'intro');
  const commandsNode = findChild(cloned, 'commands');

  if (introNode    && introNode.type    === 'TEXT') introNode.characters    = INTRO_TEXT;
  if (commandsNode && commandsNode.type === 'TEXT') commandsNode.characters = COMMANDS_TEXT;

  return {
    ok: true,
    id: cloned.id,
    x: cloned.x,
    y: cloned.y,
    introUpdated: !!(introNode    && introNode.type    === 'TEXT'),
    commandsUpdated: !!(commandsNode && commandsNode.type === 'TEXT'),
  };
})()
`;

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n  Starting Figma Console MCP server via stdio ...');
  const client = new StdioMCPClient();

  try {
    await client.start();
    console.log('  Connected.\n');

    process.stdout.write('  Creating "How to maintain this file" on Contrast Pairings page ... ');
    const t0 = Date.now();
    const result = await client.execute(FIGMA_CODE, TIMEOUT_MS);
    const elapsed = Date.now() - t0;

    if (result && result.skipped) {
      console.log('SKIPPED');
      console.log('  ' + result.message);
    } else if (result && result.ok) {
      console.log(`OK (${elapsed}ms)`);
      console.log(`  Frame id:          ${result.id}`);
      console.log(`  Position:          x=${result.x}, y=${result.y}`);
      console.log(`  intro updated:     ${result.introUpdated}`);
      console.log(`  commands updated:  ${result.commandsUpdated}`);
    } else {
      console.log(`FAILED (${elapsed}ms)`);
      console.log('  Result:', JSON.stringify(result, null, 2));
      process.exitCode = 1;
    }
  } catch (err) {
    console.error('\n  Fatal: ' + err.message);
    process.exitCode = 1;
  } finally {
    client.stop();
  }
}

main();
