FROM bit-base-images-docker-hosted.nexus.bit.admin.ch/bit/nginx-120:latest

MAINTAINER BIT-Oblique TEAM <oblique@bit.admin.ch>

LABEL io.k8s.display-name="Oblique Sandbox" \
      io.k8s.description="Frontend for Oblique Sandbox-SSR UI" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="sandbox ssr, angular, nginx, oblique"

USER root

ENV DOCROOT=/usr/share/nginx/html

# Copy the files from build step
COPY ../../dist/sandbox-ssr ${DOCROOT}

# Copy the nginx config
COPY /projects/sandbox-ssr/src/nginx/nginx.conf /etc/nginx/nginx.conf

RUN touch /var/run/nginx.pid && \
    chgrp -R 0 /var/run/nginx.pid && chmod g=u /var/run/nginx.pid && \
    chgrp -R 0 ${DOCROOT} && chmod -R g=u ${DOCROOT} && \
    chgrp -R 0 /var/log/nginx && chmod -R g=u /var/log/nginx && \
    chgrp -R 0 /etc/nginx && chmod -R g=u /etc/nginx

# Run as random openshift user
USER 1001

# Non-root users cannot open port 80, so use 8080 instead
EXPOSE 8080

ENTRYPOINT ["nginx"]
