extends: "../../.eslintrc.yml"
overrides:
  - files:
      - "*.ts"
    parserOptions:
      project:
        - projects/cli/tsconfig.app.json
        - projects/cli/tsconfig.spec.json
        - projects/cli/tsconfig.scripts.json
    rules:
      no-console:
        - error
        - allow:
            - info
            - warn
            - error
            - time
            - timeEnd
      "@typescript-eslint/no-magic-numbers":
        - error
        - ignore:
            - -1
            - 0
            - 1
  - files:
      - "*.spec.ts"
    parserOptions:
      project:
        - projects/cli/tsconfig.spec.json
    rules:
      "no-console": "off"
      "@typescript-eslint/no-magic-numbers": "off"
      "@typescript-eslint/no-unsafe-assignment": "off"
