name: Build and publish to npm

on:
  push:
    branches: [master, release/major_16.0.0]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - run: npm install -g npm@latest
      - run: npm ci
      - name: Build and publish projects
        run: |
          version="$(
            cat package.json | grep -m1 '"version"' | sed -E 's/.*"version"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/'
          )"

          if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            tag="latest"
          else
            tag="next"
          fi

          for project in cli toolchain service-navigation-web-component oblique; do
            npm run build --workspace=projects/$project
            npm publish ./dist/$project --provenance --access public --tag "$tag"
          done
