name: Publish

on:
  push:
    branches: [github-publish-test]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [oblique, sds]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://npm.pkg.github.com"
      - run: npm run -w @oblique/${{matrix.package}} lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
